config/routes.rb
H2o::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  mount RailsAdminImport::Engine => '/rails_admin_import', :as => 'rails_admin_import'

  root 'base#index'

  resources :user_sessions, :password_resets, :case_requests, :defects, 
            :case_jurisdictions, :login_notifiers, :bulk_uploads

  get 'base/embedded_pager' => 'base#embedded_pager'
  get 'all_materials' => 'base#search', as: :search_all
  get 'quick_collage' => 'base#quick_collage', as: :quick_collage
  get 'log_out' => 'user_sessions#destroy', as: :log_out
  get 'partial_results/:type' => 'base#partial_results', as: :partial_results
  get '/bookmark_item/:type/:id' => 'users#bookmark_item', as: :bookmark_item
  get '/delete_bookmark_item/:type/:id' => 'users#delete_bookmark_item', as: :delete_bookmark_item
  get '/dropbox_session' => 'dropbox_sessions#create', as: :dropbox_sessions
  get '/:klass/tag/:tag' => 'base#tags', as: :tag
  get '/p/:id' => 'pages#show'

  resources :users do
    member do
      get 'playlists'
      post 'disconnect_canvas'
      post 'disconnect_dropbox'
      get 'verification_request'
      get 'verify/:token' => 'users#verify', as: :verify
    end
    collection do
      get 'user_lookup'
    end
  end
  resources :text_blocks do
    member do
      get 'export'
    end
    collection do
      get 'embedded_pager'
    end
  end
  resources :medias do
    collection do
      get 'embedded_pager'
    end
  end
  resources :defaults do
    member do
      post 'copy'
    end
    collection do
      get 'embedded_pager'
    end
  end
  resources :playlists do
    member do
      post 'copy'
      post 'deep_copy'
      get 'push'
      get 'access_level'
      get 'export'
      post 'position_update'
      post 'private_notes'
      post 'public_notes'
      post 'toggle_nested_private'
    end
    collection do
      get 'embedded_pager'
      get 'playlist_lookup'
    end
  end
  resources :playlist_items do
    member do
      get 'delete'
    end
    collection do
      get 'block'
    end
  end
  resources :collages do
    resources :annotations
    member do
      get 'access_level'
      get 'delete_inherited_annotations'
      post 'export_unique'
      post 'save_readable_state'
      post 'copy'
      get 'collage_list'
    end
    collection do
      get 'embedded_pager'
      get 'collage_lookup'
    end
  end
  resources :cases do
    member do
      get 'access_level'
      get 'export'
      get 'embedded_pager'
      post 'approve'
    end
    collection do
      get 'embedded_pager'
    end
  end

  resources :user_collections do
    member do
      patch 'update_permissions'
      get 'manage_users'
      get 'manage_playlists'
      get 'manage_collages'
      get 'manage_permissions'
    end
  end
  
  get '/:id', :to => 'base#not_found'
end

app/models/text_block.rb
class TextBlock < ActiveRecord::Base
  include StandardModelExtensions
  include AnnotatableExtensions
  include MetadataExtensions
  include Rails.application.routes.url_helpers
  include CaptchaExtensions
  include VerifiedUserExtensions
  include DeletedItemExtensions
  include FormattingExtensions

  MIME_TYPES = {
    'text/html' => 'HTML formatted text'
  }
  RATINGS_DISPLAY = {
    :collaged => "Collaged",
    :bookmark => "Bookmarked",
    :add => "Added to"
  }

  acts_as_taggable_on :tags

  has_many :annotations, :through => :collages
  has_many :collages, :as => :annotatable
  has_many :defects, :as => :reportable
  has_many :playlist_items, :as => :actual_object, :dependent => :destroy
  belongs_to :user

  accepts_nested_attributes_for :metadatum
  validates_inclusion_of :mime_type, :in => MIME_TYPES.keys

  def self.tag_list
    Tag.find_by_sql("SELECT ts.tag_id AS id, t.name FROM taggings ts
      JOIN tags t ON ts.tag_id = t.id
      WHERE taggable_type IN ('TextBlock', 'JournalArticle')
      GROUP BY ts.tag_id, t.name
      ORDER BY COUNT(*) DESC LIMIT 25")
  end

  def display_name
    name
  end

  #Export the content that gets annotated in a Collage - also, render the content for display.
  #As always, the content method should export valid html/XHTML.
  def content
    if mime_type == 'text/plain'
      self.class.format_content(description)
    elsif mime_type == 'text/html'
      self.class.format_html(description)
    else
      self.class.format_content(description)
    end
  end

  alias :to_s :display_name

  searchable(:include => [:metadatum, :collages, :tags]) do
    text :display_name, :boost => 3.0
    string :display_name, :stored => true
    string :id, :stored => true
    text :clean_description
    boolean :active
    boolean :public
    integer :karma

    string :user
    string :user_display, :stored => true
    integer :user_id, :stored => true

    string :tag_list, :stored => true, :multiple => true
    string :collages, :stored => true, :multiple => true
    string :metadatum, :stored => true, :multiple => true

    time :created_at
    time :updated_at
  end

  def clean_description
    self.description.gsub!(/\p{Cc}/, "")
  end

  def barcode
    Rails.cache.fetch("textblock-barcode-#{self.id}", :compress => H2O_CACHE_COMPRESSION) do
      barcode_elements = self.barcode_bookmarked_added
      self.collages.each do |collage|
        barcode_elements << { :type => "collaged",
                              :date => collage.created_at,
                              :title => "Collaged to #{collage.name}",
                              :link => collage_path(collage),
                              :rating => 5 }
      end

      value = barcode_elements.inject(0) { |sum, item| sum + item[:rating] }
      self.update_attribute(:karma, value)

      barcode_elements.sort_by { |a| a[:date] }
    end
  end
end

app/controllers/text_blocks_controller.rb
class TextBlocksController < BaseController
  cache_sweeper :text_block_sweeper
  protect_from_forgery :except => [:destroy]

  def show
  end

  def export
    render :layout => 'print'
  end

  def edit
  end

  def embedded_pager
    super TextBlock
  end

  def new
    @text_block = TextBlock.new
    @text_block.build_metadatum
  end

  def create
    unless params[:text_block][:tag_list].blank?
      params[:text_block][:tag_list] = params[:text_block][:tag_list].downcase
    end

    @text_block = TextBlock.new(text_blocks_params)
    @text_block.user = current_user
    verify_captcha(@text_block)

    if @text_block.save
      flash[:notice] = 'Text Block was successfully created.'
      redirect_to "/text_blocks/#{@text_block.id}"
    else
      render :action => "new"
    end
  end

  def index
    common_index TextBlock
  end

  def update
    unless params[:text_block][:tag_list].blank?
      params[:text_block][:tag_list] = params[:text_block][:tag_list].downcase
    end

    if @text_block.update_attributes(text_blocks_params)
      flash[:notice] = 'Text Block was successfully updated.'
      redirect_to "/text_blocks/#{@text_block.id}"
    else
      render :action => "edit"
    end
  end

  def destroy
    @text_block.destroy
    render :json => {}
  end

  private
  def text_blocks_params
    params.require(:text_block).permit(:id, :name, :public, :description, :mime_type, :tag_list, 
                                       metadatum_attributes: [:contributor, :coverage, :creator, :date,
                                                              :description, :format, :identifier, :language,
                                                              :publisher, :relation, :rights, :source,
                                                              :subject, :title, :dc_type, :classifiable_type, 
                                                              :classifiable_id ])
  end
end

app/views/text_blocks/_meta.html.erb
<p>
  <label>Last Updated:</label>
  <%= @text_block.updated_at.strftime("%B %d, %Y") %>
</p>

<% if @text_block.metadatum -%>
<%= render :partial => "shared/objects/metadatum", :object => @text_block.metadatum %>
<% end -%>

<% cache(["tags", @text_block], :compress => H2O_CACHE_COMPRESSION) do -%>
<% if @text_block.tags.any? -%>
<p>
  <label>Tags:</label>
  <% @text_block.tags.each do |tag| -%>
  <%= link_to tag.name, tag_path("text_blocks", CGI.escape(tag.name)) %>
  <% end -%>
</p>
<% end -%>
<% end -%>

app/views/text_blocks/_quickbar.html.erb
<div id="quickbar">
  <div class="wrapper">
    <div id="quickbar_left">
      <a href="/" id="quickbar_logo"><%= image_tag 'h20-logo.png' %></a>
      <span id="quickbar_title">
        <%= @text_block.name %>
      </span>
      <span id="quickbar_author">
      <span>| </span><%= raw link_to(@text_block.user.display, user_path(@text_block.user)) %>
      </span>
      <span class="quickbar_extra">
      | <%= @text_block.created_at.strftime("%B %d, %Y") %>
      </span>
    </div>
    <div id="quickbar_right">
      <a href="<%= export_text_block_path(@text_block) %>" class="icon icon-black-print" id="quickbar_print" title="Print <%= @text_block.name %>"><span>Print</span></a>
      <%= link_to raw('<span class="icon icon-black-favorite"><span>Bookmark Text</span></span>'), '#', :class => "bookmark-action requires_logged_in", :title => "Bookmark #{@text_block.name}", "data-type" => "text_block", "data-itemid" => @text_block.id %>
      <a href="#" class="icon icon-black-font" id="quickbar_font" title="Change the size of the text"><span>Font Settings</span></a>
      <%= link_to raw('<span class="icon icon-tocollage-black"><span>Collage This</span></span>'), new_collage_path(:annotatable_type => 'TextBlock', :annotatable_id => @text_block), :class => 'collage-this new-action tooltip', :title => "Collage This" %>
    </div>
    <div class="clear"></div>
  </div>
</div>

app/views/text_blocks/edit.html.erb
<%= render :partial => 'shared/forms/text_block' %>

app/views/text_blocks/export.html.erb
<div id="text_block" class="singleitem" data-itemid="<%= @text_block.id %>">
  <h1><%= @text_block.display_name %></h1>
	<div class="details">
		<div class="clear"></div>
		<% cache(["detail", @text_block], :compress => H2O_CACHE_COMPRESSION) do -%>
      <% if @text_block.metadatum -%>
      <%= render :partial => 'shared/objects/metadatum', :object => @text_block.metadatum %>
      <% end -%> 
		<% end -%>
	</div>
  <div class="fontdetails"></div>
	<article>
  		<%= raw @text_block.content %>
	</article>
</div>

app/views/text_blocks/new.html.erb
<%= render :partial => 'shared/forms/text_block' %>

app/views/text_blocks/show.html.erb
<div id="fixed_links">
<a href="#" class="fixed_link left-tooltip" id="collapse_toggle" title="Text Info">Collapse/Expand</a>
<a href="<%= export_text_block_path(@text_block) %>" class="fixed_link left-tooltip" id="fixed_print" title="Print <%= @text_block.name %>">Print</a>
<a href="#" class="fixed_link left-tooltip btn-a dont_hide" id="fixed_font" title="Change the size of the text">Font Settings</a>
</div>

<aside id="singleitem_barcode_toolbar">
  <% if current_user -%>
  <%= link_to raw('<span class="icon icon-tocollage-large"><span>Collage This</span></span>'), new_collage_path(:annotatable_type => 'TextBlock', :annotatable_id => @text_block), :class => 'collage-this new-action tooltip', :title => "Collage This" %>
  <%= link_to raw('<span class="icon icon-add-large"><span>Add to Playlist</span></span>'), '#', "data-item_id" => @text_block.id, "data-type" => "text_block", :class => 'link-add tooltip requires_logged_in', :title => "Add to a Playlist" %>
  <%= link_to raw('<span class="icon icon-favorite-large"><span>Bookmark Text</span></span>'), '#', :class => "bookmark-action tooltip requires_logged_in", :title => "Bookmark #{@text_block.name}", "data-type" => "text_block", "data-itemid" => @text_block.id %>
  <% end -%>
</aside>

<div id="text_block" class="singleitem" data-itemid="<%= @text_block.id %>">
  <div id="main_details">
    <h1 class="scale1-5"><%= @text_block.display_name %></h1>
  </div>
  <% if current_user && (current_user.has_role?(:superadmin) || current_user.text_blocks.include?(@text_block)) %>
  <div id="description" class="scale1-1">
    <%= link_to raw('<span class="icon icon-edit"></span>EDIT TEXT INFORMATION<span class="icon icon-arrow"></span>'), edit_text_block_path(@text_block), :class => "edit-external scale0-8" %>
    <%= link_to raw('<span class="icon icon-delete"></span>DELETE TEXT<span class="icon icon-arrow"></span>'), @text_block, "data-type" => "text_block", "data-id" => @text_block.id, :class => "delete-action scale0-8" %>
  </div>
  <% end -%>
  <article>
    <%= raw @text_block.content %>
  </article>
</div>

<div id="stats" class="right_panel">
  <a href="#" class="right_panel_close">Close</a>
  <h3 class="info">Text Information<span class="icon icon-panel"></span></h3>
  <div class="stats_panel">
    <%= render :partial => "meta" %>
  </div>
  <h3>Author Stats</h3>
  <%= render :partial => "shared/author_stats", :locals => { :user => @text_block.user } %>
</div>

<div class="clear"></div>