config/routes.rb
H2o::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  mount RailsAdminImport::Engine => '/rails_admin_import', :as => 'rails_admin_import'

  root 'base#index'

  resources :user_sessions, :password_resets, :case_requests, :defects, 
            :case_jurisdictions, :login_notifiers, :bulk_uploads

  get 'base/embedded_pager' => 'base#embedded_pager'
  get 'all_materials' => 'base#search', as: :search_all
  get 'quick_collage' => 'base#quick_collage', as: :quick_collage
  get 'log_out' => 'user_sessions#destroy', as: :log_out
  get 'partial_results/:type' => 'base#partial_results', as: :partial_results
  get '/bookmark_item/:type/:id' => 'users#bookmark_item', as: :bookmark_item
  get '/delete_bookmark_item/:type/:id' => 'users#delete_bookmark_item', as: :delete_bookmark_item
  get '/dropbox_session' => 'dropbox_sessions#create', as: :dropbox_sessions
  get '/:klass/tag/:tag' => 'base#tags', as: :tag
  get '/p/:id' => 'pages#show'

  resources :users do
    member do
      get 'playlists'
      post 'disconnect_canvas'
      post 'disconnect_dropbox'
      get 'verification_request'
      get 'verify/:token' => 'users#verify', as: :verify
    end
    collection do
      get 'user_lookup'
    end
  end
  resources :text_blocks do
    member do
      get 'export'
    end
    collection do
      get 'embedded_pager'
    end
  end
  resources :medias do
    collection do
      get 'embedded_pager'
    end
  end
  resources :defaults do
    member do
      post 'copy'
    end
    collection do
      get 'embedded_pager'
    end
  end
  resources :playlists do
    member do
      post 'copy'
      post 'deep_copy'
      get 'push'
      get 'access_level'
      get 'export'
      post 'position_update'
      post 'private_notes'
      post 'public_notes'
      post 'toggle_nested_private'
    end
    collection do
      get 'embedded_pager'
      get 'playlist_lookup'
    end
  end
  resources :playlist_items do
    member do
      get 'delete'
    end
    collection do
      get 'block'
    end
  end
  resources :collages do
    resources :annotations
    member do
      get 'access_level'
      get 'delete_inherited_annotations'
      post 'export_unique'
      post 'save_readable_state'
      post 'copy'
      get 'collage_list'
    end
    collection do
      get 'embedded_pager'
      get 'collage_lookup'
    end
  end
  resources :cases do
    member do
      get 'access_level'
      get 'export'
      get 'embedded_pager'
      post 'approve'
    end
    collection do
      get 'embedded_pager'
    end
  end

  resources :user_collections do
    member do
      patch 'update_permissions'
      get 'manage_users'
      get 'manage_playlists'
      get 'manage_collages'
      get 'manage_permissions'
    end
  end
  
  get '/:id', :to => 'base#not_found'
end

app/views/shared/_author_stats.html.erb
<% if user.present? -%>
<div class="stats_panel">
  <p>
    <label>Name:</label>
    <span><%= user.display %></span>
  </p>
  <% if user.title.present? -%>
  <p>
    <label>Title:</label>
    <span><%= user.title %></span>
  </p>
  <% end -%>
  <% if user.affiliation.present? -%>
  <p>
    <label>Affiliation:</label>
    <span><%= user.affiliation %></span>
  </p>
  <% end -%>
  <% if user.url.present? -%>
  <p>
    <label>Website:</label>
    <span id="user_website"><%= user.url %></span>
  </p>
  <% end -%>
  <% if user.description.present? -%>
  <p>
    <label>Description:</label>
    <span><%= user.description %></span>
  </p>
  <% end -%>
</div>
<% end -%>

app/views/shared/_barcode.html.erb
<% if false && object && object.barcode.any? -%>
<% cache(["barcode-html", object], :compress => H2O_CACHE_COMPRESSION) do %>
<div class="barcode" data-karma="<%= object.karma || 0 %>" data-ticks="<%= object.barcode.size || 0 %>">
  <% if object.karma.to_i > 66 -%>
  <a class="listing_overflow overflow" href="#"></a>
  <% end -%>
  <% object.visible_barcode.each do |item| %>
  <a href="<%= item[:link] || '#' %>" target="_blank" class="<%= item[:type] %>" title="<%= item[:title] %>"><span><%= item[:title] %></span></a>
  <% end -%>
  <% if object.karma.to_i > 66 -%>
  <a class="base_index_overflow overflow" href="#"></a>
  <% end -%>
  <div class="clear"></div>
</div>
<%= render :partial => "shared/breakdown_barcode", :locals => { :model => object.class, :breakdown_data => object.barcode_breakdown } %>
<% end -%>
<% end -%>

app/views/shared/_bookmarks_block.html.erb
<% @collection.each do |bookmark| -%>
  <% item = bookmark.actual_object %>
  <%= render :partial => "shared/objects/#{item.class == Case ? 'case_obj' : item.class.to_s.downcase}",
              :locals => { :hit => item, (item.class == Case ? :case_obj : item.class.to_s.downcase.to_sym) => item } %>
<% end -%>

<div id="new_pagination" style="display:none;">
<%= will_paginate @collection, :container => false, :previous_label => 'Previous', :next_label => 'Next' %>
<div>

app/views/shared/_breakdown_barcode.html.erb
<% if breakdown_data.keys.any? -%>
<div class="barcode_breakdown">
  <% model::RATINGS_DISPLAY.each do |k, v| -%>
  <% if breakdown_data.has_key?(k) -%>
  <div class="<%= k %>">
    <span class="icon icon-<%= k %>"></span>
    <span class="detail">
      <b><%= v %></b> <%= pluralize breakdown_data[k], (k == :add ? 'playlist' : 'time') %>
    </span>
  </div>
  <% end -%>
  <% end -%>
</div>
<% end -%>

app/views/shared/_collage_link_item.html.erb
<% if @objects -%>
<%= will_paginate @objects, :previous_label => 'Previous', :next_label => 'Next' %>
  <% @display_objects.each do |hit| -%>
  <a href="#" class="add-collage-button" data-id="<%= hit.id %>"><%= hit.display_name %></a>
  <% end %>
<%= will_paginate @objects, :previous_label => 'Previous', :next_label => 'Next' %>
<% end %>

app/views/shared/_generic_collection_block.html.erb
<% @collection.each do |result| -%>
  <%= render :partial => "shared/objects/#{@view}", :locals => { @view.to_sym => result, :hit => result } %>
<% end -%>

<div id="new_pagination" style="display:none;">
<%= will_paginate @collection.is_a?(WillPaginate::Collection) ? @collection : @collection.hits, :container => false, :previous_label => 'Previous', :next_label => 'Next' %>
<div>

app/views/shared/_google_analytics.html.erb
<% if Object.const_defined?(:GOOGLE_ANALYTICS_CODE) %>
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', '<%= GOOGLE_ANALYTICS_CODE %>']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
<% end %> 

app/views/shared/_login.html.erb
<% if !current_user || @page_cache -%>
<div id="login-popup" class="standard-form popup">
  <div class="right">
    <h3>Returning user log in</h3>
    <%= form_for UserSession.new do |f| %>
    <%= f.label :login %>
    <%= f.text_field :login, :class => 'text' %>
    <%= f.label :password %>
    <%= f.password_field :password, :class => 'text' %>
    <div class="remember">
    <%= link_to 'Forgot your password?', new_password_reset_path %>
    </div>
    <div class="remember">
    <%= f.check_box :remember_me %><%= f.label :remember_me %>
    </div>
    <div class="center">
    <%= f.submit "LOGIN", :class => 'button' %>
    </div>
    <% end -%>
  </div>
  <div class="left">
    <h3>Are you a first-time user?</h3>
    <a href="/users/new/" class="button">SIGN UP NOW</a>
  </div>
</div>
<% end -%>

app/views/shared/_nav.html.erb
<header>
	<div class="wrapper">
		<nav>
			<% if @page_cache -%>
			<span id="user_account"></span>
			<%= link_to "sign out", log_out_path, :class => 'requires_logged_in' %>
			<%= link_to "sign in", new_user_session_path, :id => 'header_login', :class => 'afterload' %>
			<% else -%>
			<% if current_user -%>
			<%= link_to "#{current_user.simple_display} Dashboard", user_path(current_user), :id => "logged-in" %>
			<%= link_to "sign out", log_out_path %>
			<% else -%>
			<%= link_to "sign in", new_user_session_path, :id => 'header_login', :class => "dont_hide" %>
			<% end -%>
			<% end -%>
			<div class="clear"></div>
		</nav>
		<nav id="object_types" class="light_hover">
			<%= link_to raw('<span class="icon icon-playlist">Playlists</span>'), playlists_path, { :title => "Playlists", :class => "nav-tooltip" } %>
			<%= link_to raw('<span class="icon icon-collage">Collages</span>'), collages_path, { :title => "Collages", :class => "nav-tooltip" } %>
			<%= link_to raw('<span class="icon icon-case">Cases</span>'), cases_path, { :title => "Cases", :class => "nav-tooltip" } %>
			<%= link_to raw('<span class="icon icon-textblock">Texts</span>'), text_blocks_path, { :title => "Texts", :class => "nav-tooltip" } %>
			<%= link_to raw('<span class="icon icon-media-image">Images</span>'), "/medias?media_type=image", { :title => "Images", :class => "nav-tooltip" } %>
			<%= link_to raw('<span class="icon icon-media-audio">Audio</span>'), "/medias?media_type=audio", { :title => "Audio", :class => "nav-tooltip" } %>
			<%= link_to raw('<span class="icon icon-media-pdf">PDFs</span>'), "/medias?media_type=pdf", { :title => "PDFs", :class => "nav-tooltip" } %>
			<%= link_to raw('<span class="icon icon-media-video">Videos</span>'), "/medias?media_type=video", { :title => "Videos", :class => "nav-tooltip" } %>
			<%= link_to raw('<span class="icon icon-default">Links</span>'), defaults_path, { :title => "Links", :class => "nav-tooltip" } %>
			<%= link_to raw('<span class="icon icon-user">Users</span>'), users_path, { :title => "Users", :class => "nav-tooltip" } %>
		</nav>
		<h1 id="logo"><%= link_to "H2O", "/" %></h1>
		<section id="search">
		<%= form_tag("/all_materials", :method => :get, :class => "search") do %>
		<table>
			<tr>
				<td id="spinner">
					<%= image_tag "ajax-loader.gif" %>
				</td>
				<% if params[:controller] == 'cases' && (@page_cache || (current_user && current_user.not_anonymous)) %>
				<td class="requires_non_anonymous">
				<%= link_to "REQUEST CASE", new_case_request_path, :id => 'case_request_button', :class => 'requires-non-anonymous button' %>
				</td>
				<% end -%>
				<td class="field search">
          <label for="keywords" class="hidden-label">Keywords</label>
					<%= text_field_tag "keywords", params[:keywords], :size => 50 %>
				</td>
				<td class="search">
          <label for="search_all" class="hidden-label">Search All</label>
					<select id="search_all">
						<option value="all_materials">all</option>
            <% {"playlists" => "Playlists", "collages" => "Collages", "cases" => "Cases", "text_blocks" => "Texts", "medias" => "Media Items", "defaults" => "Links", "users" => "Users" }.each do |k, v| -%>
						<option value="<%= k %>" <%= raw 'selected="selected"' if params[:controller] == k %>><%= v %></option>
						<% end -%>
					</select>
				</td>
				<td>
					<a href="#" id="search_button" class="button">SEARCH</a>
				</td>
				<% if @page_cache || current_user -%>
				<td id="create_nav" class="requires_logged_in">
					<a href="#" id="create_all">CREATE<span></span></a>
				</td>
				<% end -%>
			</tr>
		</table>
		<% end -%>
		<div class="popup" id="create_all_popup">
			<div class="left">
			<%= link_to raw('<span class="icon icon-playlist"></span>Playlist'), new_playlist_path, :class => "new-action" %> 
			<%= link_to raw('<span class="icon icon-collage"></span>Collage'), quick_collage_path, :id => 'quick_collage' %>
			<%= link_to raw('<span class="icon icon-textblock"></span>Text'), new_text_block_path %>
			<%= link_to raw('<span class="icon icon-media-pdf"></span>PDF'), new_media_path, :class => "last" %> 
			</div>
			<div class="right">
			<%= link_to raw('<span class="icon icon-media-audio"></span>Audio'), new_media_path %> 
			<%= link_to raw('<span class="icon icon-media-image"></span>Image'), new_media_path %> 
			<%= link_to raw('<span class="icon icon-media-video"></span>Video'), new_media_path %>
			<%= link_to raw('<span class="icon icon-default"></span>Link'), new_default_path, :class => "last" %>
			</div>
		</div>
		</section>
		<div class="clear"></div>
	</div>
</header>

app/views/shared/_playlistable_item.html.erb
<% if @objects -%>
<h3>
  <%= pluralize @objects.total_entries, "Result" %> <span class="dr">(Drag and drop items)</span>
  <aside class="sort">
	  <%= render :partial => 'shared/sort', :locals => { :list => @sort_lists[@list_key] } %>
  </aside>
</h3>
<%= will_paginate @objects, :previous_label => 'Previous', :next_label => 'Next' %>
<div id="nestable2">
  <ol class="dd-list">
    <% @display_objects.each_with_index do |hit, i| -%>
    <li class="listing dd-item" data-index="<%= i %>" data-type="<%= hit.class.to_s.tableize %>" data-id="<%= hit.id %>" data-drop="new_item" id="listing_<%= hit.class.to_s.tableize %>_<%= hit.id %>">
      <div class="dd-handle">
      <a class="tooltip icon icon-<%= hit.class == Media ? "media-#{hit.media_type.slug}" : hit.class.to_s.downcase %>" title="<%= hit.class == Media ? hit.media_type.label : hit.class %>"></a>
      <h4><%= hit.display_name %></h4>
      </div>
    </li>
    <% end %>
  </ol>
</div>
<%= will_paginate @objects, :previous_label => 'Previous', :next_label => 'Next' %>
<% end %>

app/views/shared/_quickbar.html.erb
<% if @single_resource && [Case, TextBlock, Collage, Playlist].include?(@single_resource.class) && !@single_resource.new_record? -%>
<%= render :partial => "#{@single_resource.class.to_s.tableize}/quickbar" %>
<% end -%>

app/views/shared/_sort.html.erb
<% if list -%>
<label for="list-sort" class="hidden-label">Sort</label>
<select id="list-sort">
	<% list.each do |k, v| -%>
		<option value="<%= k %>" <%= raw 'selected="selected"' if v[:selected] %>><%= v[:display] %></option>
	<% end -%>
</select>
<% end -%>

app/views/shared/list_index.html.erb
<section id="results" class="multiitems">
	<aside class="sort">
		<%= render :partial => 'shared/sort', :locals => { :list => @sort_lists[@model.to_s.tableize.to_sym] } %>
	</aside>
	<div class="search_details">
		<aside class="pagination standard_pagination">
			<% if @model == Media -%>
			<%= will_paginate @collection.results, :container => false, :previous_label => 'Previous', :next_label => 'Next', :params => { :media_type => params[:media_type] } %>
			<% else -%>
			<%= will_paginate @collection.results, :container => false, :previous_label => 'Previous', :next_label => 'Next' %>
			<% end -%>
		</aside>
		<h2>
		<% if params[:tag] -%>
		<%= @label %> tagged: <%= CGI.unescape(params[:tag]) %> (<%= pluralize @collection.results.total_entries, @label %> Total)
		<%= link_to "CLEAR TAG", self.send("#{@model == Media ? "medias" : @model.to_s.tableize}_path") %>
		<% elsif params[:keywords] -%>
		Search Results: <b><%= params[:keywords] %></b>
		<p>
		(<%= pluralize @collection.results.total_entries, @label %> Total)
		</p>
		<% else -%>
		<%= pluralize @collection.results.total_entries, @label %> Total
		<% end -%>
		</h2>
	</div>
	<ul id="results_set">
		<% @collection.each_hit_with_result do |hit, result| -%>
		<%= render :partial => "shared/objects/#{@partial}", :locals => { @model_sym => result, :hit => hit } %>
		<% end -%>
	</ul>
	<div class="search_details bottom">
		<aside class="pagination standard_pagination">
			<% if @model == Media -%>
			<%= will_paginate @collection.results, :container => false, :previous_label => 'Previous', :next_label => 'Next', :params => { :media_type => params[:media_type] } %>
			<% else -%>
			<%= will_paginate @collection.results, :container => false, :previous_label => 'Previous', :next_label => 'Next' %>
			<% end -%>
		</aside>
	</div>
</section>