config/routes.rb
H2o::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  mount RailsAdminImport::Engine => '/rails_admin_import', :as => 'rails_admin_import'

  root 'base#index'

  resources :user_sessions, :password_resets, :case_requests, :defects, 
            :case_jurisdictions, :login_notifiers, :bulk_uploads

  get 'base/embedded_pager' => 'base#embedded_pager'
  get 'all_materials' => 'base#search', as: :search_all
  get 'quick_collage' => 'base#quick_collage', as: :quick_collage
  get 'log_out' => 'user_sessions#destroy', as: :log_out
  get 'partial_results/:type' => 'base#partial_results', as: :partial_results
  get '/bookmark_item/:type/:id' => 'users#bookmark_item', as: :bookmark_item
  get '/delete_bookmark_item/:type/:id' => 'users#delete_bookmark_item', as: :delete_bookmark_item
  get '/dropbox_session' => 'dropbox_sessions#create', as: :dropbox_sessions
  get '/:klass/tag/:tag' => 'base#tags', as: :tag
  get '/p/:id' => 'pages#show'

  resources :users do
    member do
      get 'playlists'
      post 'disconnect_canvas'
      post 'disconnect_dropbox'
      get 'verification_request'
      get 'verify/:token' => 'users#verify', as: :verify
    end
    collection do
      get 'user_lookup'
    end
  end
  resources :text_blocks do
    member do
      get 'export'
    end
    collection do
      get 'embedded_pager'
    end
  end
  resources :medias do
    collection do
      get 'embedded_pager'
    end
  end
  resources :defaults do
    member do
      post 'copy'
    end
    collection do
      get 'embedded_pager'
    end
  end
  resources :playlists do
    member do
      post 'copy'
      post 'deep_copy'
      get 'push'
      get 'access_level'
      get 'export'
      post 'position_update'
      post 'private_notes'
      post 'public_notes'
      post 'toggle_nested_private'
    end
    collection do
      get 'embedded_pager'
      get 'playlist_lookup'
    end
  end
  resources :playlist_items do
    member do
      get 'delete'
    end
    collection do
      get 'block'
    end
  end
  resources :collages do
    resources :annotations
    member do
      get 'access_level'
      get 'delete_inherited_annotations'
      post 'export_unique'
      post 'save_readable_state'
      post 'copy'
      get 'collage_list'
    end
    collection do
      get 'embedded_pager'
      get 'collage_lookup'
    end
  end
  resources :cases do
    member do
      get 'access_level'
      get 'export'
      get 'embedded_pager'
      post 'approve'
    end
    collection do
      get 'embedded_pager'
    end
  end

  resources :user_collections do
    member do
      patch 'update_permissions'
      get 'manage_users'
      get 'manage_playlists'
      get 'manage_collages'
      get 'manage_permissions'
    end
  end
  
  get '/:id', :to => 'base#not_found'
end

app/views/shared/objects/_case_obj.html.erb
<% cache(["list-object", case_obj], :compress => H2O_CACHE_COMPRESSION) do %>
<li class="listitem listitem<%= case_obj.id %>" id="listitem_case<%= case_obj.id %>" data-itemid="<%= case_obj.id %>" data-type="case">
  <a href="#" class="tooltip list-icon icon icon-case" title="Case"></a>
  <div class="details">
    <h3>
      <%= link_to case_obj.short_name, case_obj, :class => "title" %>
    </h3>
    <p class="cases_details">
      <%= case_obj.case_citations.collect { |c| c.display_name }.join(', ') %> /

      <% if !case_obj.decision_date.nil? -%>
      <%= case_obj.decision_date %>
      <% end -%>
    </p>
  </div>
  <div class="right_details">
  <div class="controls">
    <%= link_to raw('<span class="icon icon-read"></span>READ'), case_obj, :class => "action read-action" %>
    <%= link_to raw('<span class="icon icon-collage-this"></span>COLLAGE THIS'), new_collage_path(:annotatable_type => 'Case', :annotatable_id => case_obj), :class => "new-action link-collage" %>
    <a data-item_id="<%= case_obj.id %>" data-type="case" class="link-add" href="#"><span class="icon icon-add"></span>ADD</a>
    <%= link_to raw('<span class="icon icon-favorite"></span>BOOKMARK'), '#',
      :class => "link-bookmark bookmark-action", 
      "data-itemid" => case_obj.id,
      "data-type" => "case" %>
  </div>
  </div>
  <div class="clear"></div>
</li>
<% end -%>

app/views/shared/objects/_case_obj_print.html.erb
<p>Decision date: <%= case_obj.decision_date %></p>
<% unless case_obj.author.blank? -%>
<p>Author: <%= case_obj.author %></p>
<% end -%>
<% unless case_obj.case_citations.blank? -%>
<p>Citations: <%= case_obj.case_citations.collect{|cc| cc.display_name}.join(', ') %></p> 
<% end -%>
<% unless case_obj.case_docket_numbers.blank? -%>
<p>Docket Numbers: <%= case_obj.case_docket_numbers.collect{|cc| cc.display_name}.join(', ') %></p> 
<% end -%>
<% unless case_obj.case_jurisdiction.blank? -%>
<p>Jurisdiction: <%= case_obj.case_jurisdiction.display_name %></p> 
<% end -%>
<article>
<%= raw case_obj.content %>
</article>

app/views/shared/objects/_case_request.html.erb
<li class="listitem listitem<%= case_request.id %>" data-itemid="<%= case_request.id %>">
	<div class="details">
		<h3>
			<%= case_request.full_name %>
      <%= link_to "DELETE", case_request_path(case_request), :class => "icon icon-delete tooltip", "data-type" => "case_request", "data-id" => case_request.id %>
      <%= link_to "CREATE CASE FROM THIS REQUEST", new_case_path(:case_request_id => case_request.id), :class => "action" %>
		</h3>
		
		<p class="cases_details">
      <% [:decision_date, :author, :case_jurisdiction, :docket_number, :volume, :reporter, :page, :bluebook_citation].each do |f| -%>
			<%= f %>: <%= case_request.send(f) %><br /> 
      <% end -%>
		</p>
	</div>
  <div class="clear"></div>
</li>

app/views/shared/objects/_collage.html.erb
<% cache([collage.user, "list-object", collage], :compress => H2O_CACHE_COMPRESSION) do %>
<li class="listitem listitem<%= collage.id %>" id="listitem_collage<%= collage.id %>" data-itemid="<%= collage.id %>" data-type="collage">
  <a href="#" class="tooltip list-icon icon icon-collage" title="Collage"></a>
  <div class="details">
    <h3>
      <%= link_to collage.name, collage_path(collage), :class => "title" %>
    </h3>
    <p>
      <% if hit.stored(:user_id).present? -%>
      <% if hit.stored(:root_user_id).present? && hit.stored(:root_user_id) != hit.stored(:user_id) -%>
      Original Creator: <%= link_to hit.stored(:root_user_display), "/users/#{hit.stored(:root_user_id)}" %> |
      Current Version: <%= link_to hit.stored(:user_display), "/users/#{hit.stored(:user_id)}" %> |
      <% else -%>
      <%= link_to hit.stored(:user_display), "/users/#{hit.stored(:user_id)}" %> |
      <% end -%>
      <% end -%>
      <% if collage.words_shown.present? -%>
      <%= number_with_delimiter(collage.words_shown, :delimiter => ',') %> Words |
      <% end -%>
      <%= collage.updated_at.strftime("%B %d, %Y") %>
      <% if false -%>Taught at [school] (if it hasn't been taught anywhere, don't display this field) <% end -%>
    </p>
  </div>

  <div class="right_details">
  <div class="controls">
    <%= link_to raw('<span class="icon icon-read"></span>READ'), collage, :class => "action read-action" %>
    <a href="<%= copy_collage_path(collage) %>" class="remix-action link-copy" data-type="collage" data-title="<%= collage.name %>"><span class="icon icon-remix"></span>REMIX</a>
    <a data-item_id="<%= collage.id %>" data-type="collage" class="link-add" href="#"><span class="icon icon-add"></span>ADD</a>
    <%= link_to raw('<span class="icon icon-favorite"></span>BOOKMARK'), '#',
      :class => "link-bookmark bookmark-action", 
      "data-itemid" => collage.id,
      "data-type" => "collage" %>
  </div>
  </div>

  <div class="clear"></div>
</li>
<% end -%>

app/views/shared/objects/_collage_print.html.erb
<% if collage.present? -%>
<div class="item_description scale0-9"><%= raw collage.description %></div>
<div class="collage-content" id="collage<%= collage.id %>" data-id="<%= collage.id %>">
<div class="article">
<% cache(["editable-content", collage.annotatable], :expires_in => 2.weeks, :compress => H2O_CACHE_COMPRESSION) do %>
<%= raw collage.editable_content_v2 %>
<% end -%>
</div>
</div>
<script type="text/javascript">
var collage_data_<%= collage.id %> = <%= raw(params[:state] || collage.readable_state || "{}") %>;
var annotations_<%= collage.id %> = <%= raw collage.annotations.inject({}) { |h, a| h["a#{a.id}"] =  a.to_json(:include => :layers); h }.to_json %>;
var layer_data_<%= collage.id %> = <%= raw collage.layer_data.to_json %>;
</script>
<% end -%>

app/views/shared/objects/_content_error.html.erb
<li class="listitem listitem<%= content_error.id %>" data-itemid="<%= content_error.id %>">
	<div class="details">
    <h3>
      <% if content_error.reportable -%>
      <%= content_error.reportable_type.titleize %>: <%= link_to content_error.display_name, send("#{content_error.reportable_type.underscore}_path", content_error.reportable), :class => "title" %>
      <% else -%>
      <%= content_error.reportable_type.titleize %>: <%= content_error.display_name %>
      <% end -%>
      <%= link_to 'DELETE', content_error, :class => "icon icon-delete tooltip", "data-type" => "content_error", "data-id" => content_error.id %>
    </h3>
    <p>Reported by <%= link_to(content_error.user.display, user_path(content_error.user)) %></p>
    <p class="error"><b>Error:</b> <%= content_error.description %></p>
  </div>
	<div class="clear"></div>
</li>

app/views/shared/objects/_default.html.erb
<li class="listitem listitem<%= default.id %>" id="listitem_default<%= default.id %>" data-itemid="<%= default.id %>" data-type="default">
  <a href="#" class="tooltip list-icon icon icon-default" title="Link"></a>
	<div class="details">
    <h3>
      <%= link_to default.name, default.url, :class => "title", :target => "_blank" %>
      <% if current_user && (@is_admin[:default] || @my_belongings[:defaults].include?(default)) %>
        <%= link_to 'EDIT', edit_default_path(default), :class => "icon edit-external icon-edit tooltip", :title => "Edit" %>
      <% end %>
    </h3>
    <p>
      <%= item_date_stamp default %>
      <% if default.user -%>
      added by
      <%= link_to(default.user.display, user_path(default.user)) %>
      <% end -%>
    </p>
    <% if default.description.present? -%>
    <a href="#" class="show_default_description">(more)</a>
    <p class="default_description">
    <%= default.description %>
    <a href="#" class="hide_default_description">(less)</a>
    </p>
    <% end -%>
	</div>
  <div class="right_details">
	<% if current_user -%>
	<div class="controls">
    <a data-item_id="<%= default.id %>" data-type="default" href="#" class="link-add"><span class="icon icon-add"></span>ADD</a>
    <%= link_to raw('<span class="icon icon-remix"></span>REMIX'), 
      copy_default_path(default), 
      :class => "link-remix remix-action", 
      "data-type" => "default", 
      "data-title" => default.name %>
    <%= link_to raw('<span class="icon icon-favorite"></span>BOOKMARK'), '#',
      :class => "link-bookmark bookmark-action", 
      "data-itemid" => default.id,
      "data-type" => "default" %>
	</div>
	<% end -%>
  </div>
	<div class="clear"></div>
</li>

app/views/shared/objects/_journal_article.html.erb
<li class="listitem listitem<%= journal_article.id %>" data-itemid="<%= journal_article.id %>">
	<% if current_user -%>
	<div class="controls">
		<ul>
			<li class="link-collage"><%= link_to 'Collage This', new_collage_path(:annotatable_type => 'TextBlock', :annotatable_id => journal_article), :class => "new-action" %></li>
			<li class="link-add"><a data-item_id="<%= journal_article.id %>" data-type="journal_article" href="#">Add</a></li>
		</ul>
	</div>
	<% end -%>
	<div class="details">
    <% cache(["tags", journal_article.id], :compress => H2O_CACHE_COMPRESSION) do %>
      <div class="tags">
        <% if journal_article.tag_list.any? -%>
        | <%= raw journal_article.tag_list.collect { |tag| link_to(tag, tag_path("journal_articles", CGI.escape(tag))) }.join(', ') %>
        <% end -%>
      </div>
    <% end -%>
    <h3><%= link_to journal_article.display_name, journal_article_path(journal_article), :class => "title" %>
      <% if current_user && journal_article.deleteable? && (@is_admin[:textblock] || @my_belongings[:textblocks].include?(journal_article)) %>
        <%= link_to 'DELETE', journal_article, :class => "icon icon-delete tooltip", "data-type" => "journal_article", "data-id" => journal_article.id %>
      <% end %>
      <% if current_user && (@is_admin[:textblock] || @my_belongings[:textblocks].include?(journal_article)) %>
        <%= link_to 'EDIT', edit_journal_article_path(journal_article), :class => "icon icon-edit" %>
      <% end %>
    </h3>
    <p>
      <%= item_date_stamp journal_article %>
      by
      <%= link_to(journal_article.user.display, user_path(journal_article.user)) %>
    </p>
	</div>
	<div class="clear"></div>
</li>

app/views/shared/objects/_media.html.erb
<% cache([media.user, "list-object", media], :compress => H2O_CACHE_COMPRESSION) do %>
<li class="listitem listitem<%= media.id %>" id="listitem_media<%= media.id %>" data-itemid="<%= media.id %>" data-type="media">
  <a href="#" class="tooltip list-icon icon icon-media-<%= media.media_type.slug %>" title="<%= media.media_type.label %>"></a>
	<div class="details">
    <div class="tags">
      <% media.tag_list.each do |tag| %>
      <%= link_to tag, tag_path("medias", CGI.escape(tag)) %>
      <% end -%>
    </div>
    <h3>
      <%= link_to media.name, media_path(media), :class => "title" %>
    </h3>
    <p>
      <%= item_date_stamp media %>
      <% if hit.stored(:user_id).present? -%>
      by
      <%= link_to hit.stored(:user_display), "/users/#{hit.stored(:user_id)}" %>
      <% end -%>
    </p>
	</div>
  <div class="right_details">
	<div class="controls">
    <%= link_to raw('<span class="icon icon-read"></span>READ'), media_path(media), :class => "action read-action" %>
    <a data-item_id="<%= media.id %>" data-type="media" href="#" class="link-add"><span class="icon icon-add"></span>ADD</a>
    <%= link_to raw('<span class="icon icon-favorite"></span>BOOKMARK'), '#',
      :class => "link-bookmark bookmark-action", 
      "data-itemid" => media.id,
      "data-type" => "media" %>
	</div>
  </div>
	<div class="clear"></div>
</li>
<% end -%>

app/views/shared/objects/_pending_case.html.erb
<li class="listitem listitem<%= pending_case.id %>" data-itemid="<%= pending_case.id %>">
  <a href="#" class="tooltip list-icon icon icon-case" title="Pending Case"></a>
  <div class="details">
    <h3>
      <%= pending_case.short_name %>
      <%= link_to "DELETE", case_path(pending_case), :class => "icon icon-delete tooltip", :title => "Delete", "data-type" => "case", "data-id" => pending_case.id %>
      <%= link_to "EDIT", edit_case_path(pending_case), :class => "icon edit-external icon-edit tooltip", :title => "Edit" %>
      <% if current_user.has_role?(:case_admin) %>
      <%= link_to "APPROVE", approve_case_path(pending_case), :class => "icon icon-approve action approve-action tooltip", :title => "Approve" %>
      <% end -%>
    </h3>
    <p class="cases_details">
      <%= pending_case.case_citations.collect { |c| c.display_name }.join(', ') %> /

      <% if !pending_case.decision_date.nil? -%>
      <%= pending_case.decision_date %>
      <% end -%>
    </p>
    <div class="influence"></div>
  </div>
  <div class="clear"></div>
</li>

app/views/shared/objects/_playlist.html.erb
<% cache([playlist.user, "list-object", playlist], :compress => H2O_CACHE_COMPRESSION) do %>
<li class="listitem listitem<%= hit.stored(:id) %>" id="listitem_playlist<%= hit.stored(:id) %>" data-itemid="<%= hit.stored(:id) %>" data-type="playlist">
  <a href="#" class="tooltip list-icon icon icon-playlist" title="Playlist">Playlist</a>
  <div class="details">
    <h3>
      <%= link_to raw(playlist.name), playlist, :class => "title" %>
    </h3>
    <p>
      <% if hit.stored(:user_id).present? -%>
      <% if hit.stored(:root_user_id).present? && hit.stored(:root_user_id) != hit.stored(:user_id) -%>
      Original Creator: <%= link_to hit.stored(:root_user_display), "/users/#{hit.stored(:root_user_id)}" %> |
      Current Version: <%= link_to hit.stored(:user_display), "/users/#{hit.stored(:user_id)}" %> |
      <% else -%>
      <%= link_to hit.stored(:user_display), "/users/#{hit.stored(:user_id)}" %> |
      <% end -%>
      <% end -%>
      <%= number_with_delimiter(playlist.collage_word_count[0], :delimiter => ',') %> Words |
      <%= playlist.updated_at.strftime("%B %d, %Y") %>
    </p>
  </div>

  <div class="right_details">
  <div class="controls">
    <%= link_to raw('<span class="icon icon-read"></span>READ'), playlist, :class => "action read-action" %>
    <%= link_to raw('<span class="icon icon-remix"></span>REMIX'), copy_playlist_path(playlist), :class => "link-remix remix-option-action", "data-type" => "playlist", "data-title" => playlist.name %>
    <%= link_to raw('<span class="icon icon-push"></span>PUSH'), push_playlist_path(playlist), :class => "push-action" %>
    <a data-item_id="<%= playlist.id %>" data-type="playlist" href="#" class="link-add"><span class="icon icon-add"></span>ADD</a>
    <%= link_to raw('<span class="icon icon-favorite"></span>BOOKMARK'), '#',
      :class => "link-bookmark bookmark-action", 
      "data-itemid" => playlist.id,
      "data-type" => "playlist" %>
  </div>
  </div>

  <div class="clear"></div>
</li>
<% end -%>

app/views/shared/objects/_playlist_item.html.erb
<li class="dd-item <%= actual_object.class.to_s.downcase %> listitem level<%= recursive_level %> listitem<%= item.id %> <%= 'last' if last %>" id="playlist_item_<%= item.id %>" data-itemid="<%= item.id %>" data-user_id="<%= actual_object.present? ? actual_object.user_id : 'n/a' %>" data-actual_object_id="<%= item.actual_object_id %>" data-nestable="false">
  <div class="wrapper <%= "missing_item" if actual_object.nil? %>">
  <div class="inner-wrapper dd-handle">
    <table><tr>
      <td class="width_<%= (recursive_level + 1)*11 %> number"><%= parent_index == '' ? "#{index}" : "#{parent_index}.#{index}" %></td>
      <td class="icon-cell">
        <% if item.actual_object_type == 'Media' && actual_object -%>
        <a href="#" class="tooltip icon icon-media-<%= actual_object.media_type.slug %>" title="<%= actual_object.media_type.label %>"></a>
        <% else -%>
        <a href="#" class="<%= "tooltip" if actual_object.present? %> icon icon-<%= item.clean_type %>" title="<%= actual_object.is_a?(Default) ? "Link" : actual_object.class %>"></a>
        <% end -%>
      </td>
      <td class="rr-cell">
        <% if item.render_dropdown -%>
        <%= link_to 'Show/Hide More', '#', :class => 'rr rr-closed', :id => "rr#{item.id}" %>
        <% end -%>
      </td>
      <td class="title-cell">
        <% if actual_object.present? && item.actual_object_type == 'Default' -%>
        <%= link_to item.name, actual_object.url, :target => '_blank', :class => "title #{"private" if !actual_object.public}" %>
        <% elsif actual_object.present? && item.actual_object_type == 'Media' -%>
        <%= link_to item.name, media_path(actual_object), :target => '_blank', :class => "title #{"private" if !actual_object.public}" %>
        <% elsif actual_object.present? -%>
        <%= link_to raw(item.name), actual_object, :target => '_blank', :class => "title #{"private" if !actual_object.public}" %>
        <% else -%>
        <%= item.name %> <span class="missing_item">[This resource no longer exists on H2O because its owner deleted it.]</span>
        <% end -%>
        <%= link_to raw('<span class="icon icon-delete"></span>'), url_for(:controller => 'playlist_items', :action => 'destroy', :id => item),
          :class => "action delete-playlist-item requires_remove" %>
        <%= link_to raw('<span class="icon icon-edit"></span>'), url_for(:controller => 'playlist_items', :action => 'edit', :id => item), 
          :class => "action edit-playlist-item requires_edit" %>
      </td>
    </tr></table>
    <% if item.render_dropdown -%>
    <div class="additional_details">
      <% if actual_object.present? && [Playlist, Collage].include?(actual_object.class) -%>
      <span class="creator_details">
        Original Creator: <%= link_to(actual_object.root.user.simple_display, user_path(actual_object.root.user), :class => "author_link") %>
      </span>
      <% if actual_object.root != actual_object -%>
      <span class="creator_details">
      Current Version: <%= link_to(actual_object.user.simple_display, user_path(actual_object.user), :class => "author_link") %>
      </span>
      <% end -%>
      <% end -%>

      <% if actual_object.respond_to?(:description) && actual_object.description != item.description -%>
      <div class="item_desc">
        <%= raw PlaylistItem.format_content(item.description) %>
      </div>
      <% end -%>
      <% if item.notes.to_s != '' && item.public_notes -%>
      <div class="notes">
        <b>Additional Notes:</b><br /><%= PlaylistItem.format_content(item.notes) %>
      </div>
      <% end -%>
      <% if actual_object.respond_to?(:description) && !actual_object.is_a?(TextBlock) && actual_object.description != '' -%>
      <div class="actual_obj_desc">
        <%= PlaylistItem.format_content(actual_object.description) %>
      </div>
      <% end -%>
    </div>
    <% end -%>
  </div>
  </div>
    <% if recursive_level < 4 && item.actual_object_type == 'Playlist' && @nested_playlists.has_key?("Playlist-#{item.actual_object_id}") %>
      <% nested_playlist = @nested_playlists["Playlist-#{item.actual_object_id}"] %> 
      <% if nested_playlist.playlist_items.any? -%>
      <div class="dd playlists">
        <ol class="dd-list">
        <% nested_playlist.playlist_items.each_with_index do |nested_item, nested_index| -%>
          <%= render :partial => 'shared/objects/playlist_item',
            :locals => { :item => nested_item,
            :actual_object => nested_item.actual_object,
            :parent_index => parent_index == '' ? index : "#{parent_index}.#{index}",
            :index => nested_index + 1,
            :recursive_level => recursive_level + 1,
            :last => (nested_item == nested_playlist.playlist_items.last) } %>
        <% end -%>
        </ol>
      </div>
      <% end -%>
    <% end -%>
 </li>

app/views/shared/objects/_user.erb
<li class="listitem listitem<%= user.id %>" id="listitem_collage<%= user.id %>" data-itemid="<%= user.id %>">
  <a href="#" class="tooltip list-icon icon icon-user" title="User"></a>
  <div class="details">
    <h3>
      <%= link_to user.simple_display, user_path(user), :class => "title" %>
    </h3>
    <p>
    </p>
  </div>

  <div class="right_details">
  <% if current_user %>
  <div class="controls">
    <%= link_to raw('<span class="icon icon-read"></span>READ'), user, :class => "action read-action" %>
  </div>
  <% end %>
  </div>
  <div class="clear"></div>
</li>

app/views/shared/objects/_user_collection.html.erb
<% if !user_collection.nil? -%>
<li class="listitem listitem<%= user_collection.id %>" data-itemid="<%= user_collection.id %>">
	<div class="controls">
		<ul>
		</ul>
	</div>
	<div class="details">
		<h3>
			<%= link_to user_collection.name, user_collection_path(user_collection), :class => "title" %>
			<%= link_to 'EDIT', edit_user_collection_path(user_collection), :class => "icon icon-edit tooltip" %>
			<%= link_to 'DELETE', user_collection, :class => "icon icon-delete tooltip" %>
		</h3>
		<p>
      <%= user_collection.description %>
		</p>
		<p class="extra">
			Users: <%= user_collection.users.map { |b| b.email_address }.join(', ') %><br />
			<%= link_to 'MANAGE USERS', manage_users_user_collection_path(user_collection), :class => "action edit-action" %><br />
			Playlists: <%= user_collection.playlists.map { |b| b.name }.join(', ') %><br />
			<%= link_to 'MANAGE PLAYLISTS', manage_playlists_user_collection_path(user_collection), :class => "action edit-action manage-playlists" %><br />
			Collages: <%= user_collection.collages.map { |b| b.name }.join(', ') %><br />
			<%= link_to 'MANAGE COLLAGES', manage_collages_user_collection_path(user_collection), :class => "action edit-action manage-collages" %>
		</p>
		<p class="extra extra<%= user_collection.id %> manage_permissions">
			<%= link_to 'MANAGE PERMISSIONS', manage_permissions_user_collection_path(user_collection), :class => "action edit-action" %>
		</p>
	</div>
	<div class="clear"></div>
</li>
<% end -%>