config/routes.rb
H2o::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  mount RailsAdminImport::Engine => '/rails_admin_import', :as => 'rails_admin_import'

  root 'base#index'

  resources :user_sessions, :password_resets, :case_requests, :defects, 
            :case_jurisdictions, :login_notifiers, :bulk_uploads

  get 'base/embedded_pager' => 'base#embedded_pager'
  get 'all_materials' => 'base#search', as: :search_all
  get 'quick_collage' => 'base#quick_collage', as: :quick_collage
  get 'log_out' => 'user_sessions#destroy', as: :log_out
  get 'partial_results/:type' => 'base#partial_results', as: :partial_results
  get '/bookmark_item/:type/:id' => 'users#bookmark_item', as: :bookmark_item
  get '/delete_bookmark_item/:type/:id' => 'users#delete_bookmark_item', as: :delete_bookmark_item
  get '/dropbox_session' => 'dropbox_sessions#create', as: :dropbox_sessions
  get '/:klass/tag/:tag' => 'base#tags', as: :tag
  get '/p/:id' => 'pages#show'

  resources :users do
    member do
      get 'playlists'
      post 'disconnect_canvas'
      post 'disconnect_dropbox'
      get 'verification_request'
      get 'verify/:token' => 'users#verify', as: :verify
    end
    collection do
      get 'user_lookup'
    end
  end
  resources :text_blocks do
    member do
      get 'export'
    end
    collection do
      get 'embedded_pager'
    end
  end
  resources :medias do
    collection do
      get 'embedded_pager'
    end
  end
  resources :defaults do
    member do
      post 'copy'
    end
    collection do
      get 'embedded_pager'
    end
  end
  resources :playlists do
    member do
      post 'copy'
      post 'deep_copy'
      get 'push'
      get 'access_level'
      get 'export'
      post 'position_update'
      post 'private_notes'
      post 'public_notes'
      post 'toggle_nested_private'
    end
    collection do
      get 'embedded_pager'
      get 'playlist_lookup'
    end
  end
  resources :playlist_items do
    member do
      get 'delete'
    end
    collection do
      get 'block'
    end
  end
  resources :collages do
    resources :annotations
    member do
      get 'access_level'
      get 'delete_inherited_annotations'
      post 'export_unique'
      post 'save_readable_state'
      post 'copy'
      get 'collage_list'
    end
    collection do
      get 'embedded_pager'
      get 'collage_lookup'
    end
  end
  resources :cases do
    member do
      get 'access_level'
      get 'export'
      get 'embedded_pager'
      post 'approve'
    end
    collection do
      get 'embedded_pager'
    end
  end

  resources :user_collections do
    member do
      patch 'update_permissions'
      get 'manage_users'
      get 'manage_playlists'
      get 'manage_collages'
      get 'manage_permissions'
    end
  end
  
  get '/:id', :to => 'base#not_found'
end

app/controllers/playlists_controller.rb
require 'net/http'
require 'uri'

class PlaylistsController < BaseController
  protect_from_forgery except: [:position_update, :private_notes, :public_notes, :destroy, :copy, :deep_copy, :toggle_nested_private]
  
  cache_sweeper :playlist_sweeper
  caches_page :show, :export, :if => Proc.new { |c| c.instance_variable_get('@playlist').present? && c.instance_variable_get('@playlist').public? }

  def embedded_pager
    super Playlist
  end

  def access_level 
    if current_user
      can_edit = current_user.has_role?(:superadmin) || @playlist.owner?
      can_position_update = can_edit || current_user.can_permission_playlist("position_update", @playlist)
      can_edit_notes = can_edit || current_user.can_permission_playlist("edit_notes", @playlist)
      can_edit_desc = can_edit || current_user.can_permission_playlist("edit_descriptions", @playlist)

      playlist_items = PlaylistItem.unscoped.where(playlist_id: @playlist.id)
      notes = can_edit_notes ? playlist_items : playlist_items.select { |pi| !pi.public_notes }
      nested_private_count_owned = 0
      nested_private_count_nonowned = 0
      if can_edit
        nested_private_resources = @playlist.nested_private_resources
        nested_private_count_owned = nested_private_resources.select { |i| i.user_id == @playlist.user_id }.size
        nested_private_count_nonowned = nested_private_resources.size - nested_private_count_owned
      end
      render :json => {
        :can_edit                       => can_edit,
        :notes                          => can_edit_notes ? notes.to_json(:only => [:id, :notes, :public_notes]) : "[]",
        :can_position_update            => can_position_update,
        :can_edit_notes                 => can_edit_notes,
        :custom_block                   => 'playlist_afterload',
        :can_edit_desc                  => can_edit_desc,
        :nested_private_count_owned     => nested_private_count_owned,
        :nested_private_count_nonowned  => nested_private_count_nonowned,
        :is_superadmin                  => current_user.has_role?(:superadmin)
      }
    else
      render :json => {
        :can_edit             => false,
        :notes                => [],
        :can_position_update  => false,
        :can_edit_notes       => false,
        :custom_block         => 'playlist_afterload',
        :can_edit_desc        => false, 
        :is_superadmin        => false
      }
    end
  end

  def index
    common_index Playlist
  end

  # GET /playlists/1
  def show
    nested_ps = Playlist.includes(:playlist_items).where(id: @playlist.all_actual_object_ids[:Playlist])
    @nested_playlists = nested_ps.inject({}) { |h, p| h["Playlist-#{p.id}"] = p; h }

    @page_cache = true if @playlist.public?
    @editability_path = access_level_playlist_path(@playlist)
    @author_playlists = @playlist.user.playlists.paginate(:page => 1, :per_page => 5)
    @can_edit = current_user && (current_user.has_role?(:superadmin) || @playlist.owner?)
  end

  # GET /playlists/new
  def new
    @playlist = Playlist.new
    @can_edit_all = @can_edit_desc = true
  end

  def edit
    if @playlist.nil? || @playlist.user.nil?
      redirect_to root_url
      return
    end

    if current_user
      @can_edit_all = current_user.has_role?(:superadmin) || @playlist.owner?
      @can_edit_desc = @can_edit_all || current_user.can_permission_playlist("edit_descriptions", @playlist)
    else
      @can_edit_all = @can_edit_desc = false
    end
  end

  # POST /playlists
  def create
    @playlist = Playlist.new(playlist_params)
    @playlist.user = current_user
    verify_captcha(@playlist)

    if @playlist.save
      #IMPORTANT: This reindexes the item with author set
      @playlist.index!

      render :json => { :type => 'playlists', :id => @playlist.id, :modify_playlists_cookie => true, :name => @playlist.name }
    else
      render :json => { :type => 'playlists', :id => @playlist.id, :error => true, :message => "Could not create playlist, with errors: #{@playlist.errors.full_messages.join(',')}" }
    end
  end

  # PUT /playlists/1
  def update
    if current_user
      can_edit_all = current_user.has_role?(:superadmin) || @playlist.owner?
      can_edit_desc = can_edit_all || current_user.can_permission_playlist("edit_descriptions", @playlist)
    else
      can_edit_all = can_edit_desc = false
    end
    if !can_edit_all
      params["playlist"].delete("name")  
      params["playlist"].delete("tag_list")  
      params["playlist"].delete("when_taught")
      params["playlist"].delete("location_id")
    end

    if @playlist.update_attributes(playlist_params)
      render :json => { :type => 'playlists', :id => @playlist.id }
    else
      render :json => { :type => 'playlists', :id => @playlist.id, :error => true, :message => "#{@playlist.errors.full_messages.join(', ')}" }
    end
  end

  def destroy
    @playlist.destroy

    render :json => { :success => true, :id => params[:id].to_i }
  rescue Exception => e
    render :json => { :success => false, :error => "Could not delete #{e.inspect}" }
  end

  def push
    if request.get?
      @collections = current_user.present? ? current_user.collections : []
    else    
      @collection = UserCollection.where(id: params[:user_collection_id]).first
      @playlist_pusher = PlaylistPusher.new(:playlist_id => @playlist.id, :user_ids => @collection.users.map(&:id))
      @playlist_pusher.delay.push!
      respond_to do |format|
        format.json { render :json => {:custom_block => 'push_playlist'} }
        format.js { render :text => nil }
        format.html { redirect_to(playlists_url) }
      end      
    end
  end
 
  def deep_copy
    @playlist_pusher = PlaylistPusher.new(:playlist_id => params[:id], 
                                          :user_ids => [current_user.id], 
                                          :email_receiver => 'destination',
                                          :playlist_name_override => params[:playlist][:name],
                                          :public_private_override => params[:playlist][:public])
    @playlist_pusher.delay.push!

    render :json => { :custom_block => "deep_remix_response" }
  end

  def copy
    begin
      @playlist = Playlist.where(id: params[:id]).first
      @playlist_copy = Playlist.new(playlist_params)
      @playlist_copy.parent = @playlist
      @playlist_copy.karma = 0
      @playlist_copy.user = current_user
      verify_captcha(@playlist_copy)
 
      if @playlist_copy.save
        # Note: Building empty playlist barcode to reduce cache lookup, optimize
        Rails.cache.fetch("playlist-barcode-#{@playlist_copy.id}", :compress => H2O_CACHE_COMPRESSION) { [] }
  
        @playlist_copy.playlist_items << @playlist.playlist_items.collect { |item| 
          new_item = item.clone
          new_item.save!
          new_item
        }
  
        render :json => { :type => 'playlists', :id => @playlist_copy.id, :modify_playlists_cookie => true, :name => @playlist_copy.name  } 
      else
        render :json => { :type => 'playlists', :message => "Could not create playlist, with errors: #{@playlist_copy.errors.full_messages.join(',')}", :error => true }
      end
    rescue Exception => e
      Rails.logger.warn "Failure in playlist copy: #{e.inspect}"
      render :json => { :type => 'playlists'}, :status => :unprocessable_entity 
    end
  end

  def position_update
    playlist_order = (params[:playlist_order].split("&"))
    playlist_order.collect!{|x| x.gsub("playlist_item[]=", "")}
 
    playlist = Playlist.where(id: params[:id]).first
    playlist_items = PlaylistItem.unscoped.where(playlist_id: params[:id])
    return_hash = {}
    playlist_order.each_index do |item_index|
      pi = playlist_items.detect { |pi| pi.id == playlist_order[item_index].to_i }
      if pi.present?
        pi.update_column(:position, item_index + playlist.counter_start)
        return_hash[pi.id] = item_index + playlist.counter_start
      end
    end

    render :json => return_hash.to_json
  end

  def export
    all_actual_object_ids = @playlist.all_actual_object_ids
    @preloaded_collages = @preloaded_cases = {}
    [Collage, Case].each do |model|
      item_ids = all_actual_object_ids[model.to_s.to_sym]
      if item_ids.any?
        if model == Collage
          items = model.includes(:annotatable, :color_mappings, :annotations => [:layers, :taggings => :tag]).where(id: item_ids)
          items.each do |item|
            @preloaded_collages["collage#{item.id}"] = item
          end
        elsif model == Case
          items = model.includes(:case_citations, :case_docket_numbers).where(id: item_ids)
          items.each do |item|
            @preloaded_cases["case#{item.id}"] = item
          end
        end
      end
    end

    render :layout => 'print'
  end

  def public_notes
    update_notes(true, @playlist)
  end
  def private_notes
    update_notes(false, @playlist)
  end

  def update_notes(value, playlist)
    playlist.playlist_items.each { |pi| pi.update_attribute(:public_notes, value) } 

    render :json => {  :total_count => playlist.playlist_items.count,
                       :public_count => playlist.public_count,
                       :private_count => playlist.private_count
                     }
  end

  def playlist_lookup
    render :json => { :items => @current_user.playlists.collect { |p| { :display => p.name, :id => p.id } } }
  end

  def toggle_nested_private
    @playlist.toggle_nested_private

    render :json => { :updated_count => @playlist.nested_private_resources.count }
  end

  private
  def playlist_params
    params.require(:playlist).permit(:name, :public, :tag_list, :description, :counter_start)
  end
end

app/views/playlists/_meta.html.erb
<p>
  <label>Last Updated:</label>
  <span id="autosave"><%= @playlist.updated_at.strftime("%B %d, %Y") %></span>
</p>

<% if @playlist.tags.any? -%>
<p>
  <label>Tags:</label>
  <% @playlist.tags.each do |tag| -%>
  <%= link_to tag.name, tag_path("playlists", CGI.escape(tag.name)) %>
  <% end -%>
</p>
<% end -%>

app/views/playlists/_quickbar.html.erb
<div id="quickbar">
  <div class="wrapper">
    <div id="quickbar_left">
      <a href="/" id="quickbar_logo"><%= image_tag 'h20-logo.png' %></a>
      <span id="quickbar_title">
        <%= @playlist.name %>
      </span>
      <span id="quickbar_author">
      <span>| </span><%= link_to(@playlist.user.display, user_path(@playlist.user)) %>
      </span>
      <span class="quickbar_extra">
      | <%= @playlist.created_at.strftime("%B %d, %Y") %>
      </span>
    </div>
    <div id="quickbar_right">
      <a href="#" id="quickbar_edit_toggle"><span>EDIT TOGGLE</span></a>
      <a href="<%= export_playlist_path(@playlist) %>" class="icon icon-black-print" id="quickbar_print" title="Print <%= @playlist.name %>"><span>Print</span></a>
      <%= link_to raw('<span class="icon icon-black-favorite"><span>Bookmark Playlist</span></span>'), '#', :class => "bookmark-action requires_logged_in", :title => "Bookmark #{@playlist.name}", "data-type" => "playlist", "data-itemid" => @playlist.id %>
      <a href="#" class="icon icon-black-font" id="quickbar_font" title="Change the size of the text"><span>Font Settings</span></a>
      <a href="<%= copy_playlist_path(@playlist) %>" class="remix-option-action requires_logged_in icon icon-black-remix" id="quickbar_copy-playlist" title="Remix <%= @playlist.name %>" data-type="playlist" data-title="<%= @playlist.name %>"><span>Remix</span></a>
    </div>
    <div class="clear"></div>
  </div>
</div>

app/views/playlists/edit.html.erb
<%= render :partial => 'shared/forms/playlist' %>

app/views/playlists/export.html.erb
<div id="playlist" class="singleitem" data-itemid="<%= @playlist.id %>">
	<hgroup class="description">
		<h1 class="scale1-5"><%= raw @playlist.name %></h1>
	</hgroup>
	<div class="details">
		<h2 class="scale0-8">
			<%= @playlist.updated_at.strftime("%B %d, %Y") %>
			by <a href="#" class="scale0-8"><%= link_to(@playlist.user.display, user_path(@playlist.user)) %>
		</h2>
		<div id="description" class="item_description">
			<%= Playlist.format_content(@playlist.description) %>
		</div>
	</div>
  <div class="fontdetails"></div>
	<%= render :partial => 'playlist_items/playlist_items_block_print', :locals => {:playlist => @playlist} %>
</div>

app/views/playlists/new.html.erb
<%= render :partial => 'shared/forms/playlist', :locals => { :playlist_object => @playlist } %>

app/views/playlists/prepare_copy.html.erb
<%= render :partial => 'shared/forms/playlist_copy' %>

app/views/playlists/push.html.erb
<%= render :partial => 'shared/forms/playlist_push' %>

app/views/playlists/show.html.erb
<div id="fixed_links">
<a href="#" class="fixed_link left-tooltip" id="collapse_toggle" title="Playlist Info">Collapse/Expand</a>
<a href="#" class="fixed_link requires_edit left-tooltip" id="edit_toggle" title="Edit/Read">Edit/View</a>
<a href="<%= export_playlist_path(@playlist) %>" class="fixed_link left-tooltip" id="fixed_print" title="Print <%= @playlist.name %>">Print</a>
<a href="#" class="fixed_link left-tooltip btn-a dont_hide" id="fixed_font" title="Change the size of the text">Font Settings</a>
</div>

<aside id="singleitem_barcode_toolbar">
  <%= link_to raw('<span class="icon icon-remix-large"><span>Remix Playlist</span></span>'), copy_playlist_path(@playlist), :class => "tooltip link-remix remix-option-action requires_logged_in", :title => "Remix #{@playlist.name}", "data-type" => "playlist", "data-title" => @playlist.name %>
  <%= link_to raw('<span class="icon icon-add-large"><span>Add to Playlist</span></span>'), '#', "data-item_id" => @playlist.id, "data-type" => "playlist", :class => 'link-add tooltip requires_logged_in', :title => "Add to a Playlist" %>
  <%= link_to raw('<span class="icon icon-favorite-large"><span>Bookmark Playlist</span></span>'), '#', :class => "bookmark-action tooltip requires_logged_in", :title => "Bookmark #{@playlist.name}", "data-type" => "playlist", "data-itemid" => @playlist.id %>
</aside>

<div id="playlist" class="singleitem" data-itemid="<%= @playlist.id %>">
  <div id="main_details">
    <h1 class="scale1-5"><span><%= raw @playlist.name %></span></h1>
    <h3 class="scale1-5 <%= @playlist.root != @playlist ? 'with_creators' : '' %>">
      <% if @playlist.root != @playlist -%>
      <span class="creator_details">
        <span>Original Creator: </span><%= raw link_to(@playlist.root.user.display, user_path(@playlist.root.user)) %>
      </span>
      <span class="creator_details">
        <span>Current Version: </span><%= link_to(@playlist.user.display, user_path(@playlist.user)) %>
      </span>
      <% else -%>
      <span>by </span><%= link_to(@playlist.user.display, user_path(@playlist.user)) %>
      <% end -%>
      <a href="#" id="main-wedge">Show/Hide</a>
    </h3>
  </div>
  <div id="description" class="scale1-1">
    <%= raw Playlist.format_content(@playlist.description) %>
    <%= link_to raw('<span class="icon icon-edit"></span>EDIT PLAYLIST INFORMATION<span class="icon icon-arrow"></span>'), edit_playlist_path(@playlist), :class => "edit-action requires_edit scale0-8" %>
    <%= link_to raw('<span class="icon icon-delete"></span>DELETE PLAYLIST<span class="icon icon-arrow"></span>'), @playlist, "data-type" => "playlist", "data-id" => @playlist.id, :class => "delete-action requires_edit scale0-8" %>
    <p id="public_private_instruction" class="requires_edit">Edit playlist item notes below to have a mix of public & private notes, or:</p>
    <a href="#" id="public-notes" class="requires_edit scale0-8<%= " inactive" if @playlist.public_count == @playlist.total_count %>" data-type="public"><span class="icon icon-setup"></span>MAKE ALL NOTES PUBLIC <span class="count">(<span><%= "#{@playlist.public_count}/#{@playlist.total_count}" %></span> playlist item notes are public)</span></a>
    <a href="#" id="private-notes" class="requires_edit scale0-8<%= " inactive" if @playlist.private_count == @playlist.total_count %>" data-type="private"><span class="icon icon-setup"></span>MAKE ALL NOTES PRIVATE <span class="count">(<span><%= "#{@playlist.private_count}/#{@playlist.total_count}" %></span> playlist item notes are private)</span></a>
  </div>
  <%= render :partial => 'playlist_items/playlist_items_block', :locals => {:playlist => @playlist} %>
</div>

<div id="stats" class="right_panel">
  <a href="#" class="right_panel_close">Close</a>
  <h3 class="info">Playlist Information<span class="icon icon-panel"></span></h3>
  <div class="stats_panel">
  <%= render :partial => 'meta' %>
  </div>
  <h3>Author Stats</h3>
  <%= render :partial => "shared/author_stats", :locals => { :user => @playlist.user } %>
  <h3>Other Playlists by <%= @playlist.user.simple_display %></h3>
  <div class="stats_panel" id="author_playlists">
  <%= render :partial => "partial_results/author_playlists" %>
  </div>
</div>

<div id="edit_item" class="requires_edit right_panel">
  <a href="#" class="right_panel_close"></a>
  <table class="tabs"><tr>
    <td><a id="find_items_tab" class="current" href="#">Find Items</a></td>
    <td></td>
  </tr></table>
  <div id="find_items" class="tab_panel new_item">
    <p class="instruction">
      Search below to find items, then drag and drop items
      onto playlists you own. To add items to nested playlists,
      you must first expand those playlists.
    </p>
    <div id="search_wrapper_outer">
      <a id="add_item_search" href="#">SEARCH</a>
      <div id="select_wrapper">
      <select id="add_item_select">
        <option value="base">all</option>
        <option value="cases">cases</option>
        <option value="collages">collages</option>
        <option value="medias">medias</option>
        <option value="playlists">playlists</option>
        <option value="text_blocks">texts</option>
        <option value="defaults">links</option>
      </select>
      </div>
      <div id="search_wrapper">
      <input id="add_item_term" />
      </div>
    </div>
  </div>
  <div id="add_item_results"></div>
</div>

<div class="clear"></div>

<script type="text/javascript">
var playlist_id = <%= @playlist.id %>;
var editability_path = "<%= access_level_playlist_path(@playlist) %>"; 
</script>